---
abstract: 'Modules I find handy from time to time...'
author:
  - 'Glenn Fowler <cebjyre@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200001, CPAN::Meta::Converter version 2.110330'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-Cebjyre
requires:
  CGI::Session: 0
  Cache::Memcached::Fast: 0
  Email::MIME: 0
  Email::Sender: 0
  File::chdir: 0
  JSON: 0
  Log::Log4perl: 0
  MIME::Parser: 0
  Mail::IMAPClient: 3.21
  Module::Find: 0
  Net::LDAP: 0
  Net::Server::Mail: 0
  Telephony::CountryDialingCodes: 0
  Template: 0
  Text::Context: 0
  Tie::SecureHash: 0
  XML::Quote: 0
resources:
  repository: http://github.com/cebjyre/Task-BeLike-Cebjyre
version: 0.2.0
