---
abstract: 'Modules I find handy from time to time...'
author:
  - 'Glenn Fowler <cebjyre@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-Cebjyre
requires:
  App::Ack: 0
  App::Whatsit: 0
  CGI::Session: 0
  CPAN::Reporter: 0
  Cache::Memcached::Fast: 0
  Dist::Zilla::Plugin::TaskWeaver: 0
  Dist::Zilla::PluginBundle::CEBJYRE: 0
  Email::MIME: 0
  Email::Sender: 0
  File::chdir: 0
  JSON: 0
  LWP::Protocol::https: 0
  Log::Log4perl: 0
  MIME::Parser: 0
  Mail::IMAPClient: 3.21
  Module::Find: 0
  MongoDB: 0
  Net::Google::FederatedLogin: 0
  Net::LDAP: 0
  Net::OAuth: 0
  Net::Server::Mail: 0
  Telephony::CountryDialingCodes: 0
  Template: 0
  Term::ReadLine::Perl: 0
  Test::ConsistentVersion: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Reporter::Transport::Metabase: 0
  Text::Context: 0
  Tie::SecureHash: 0
  Try::Tiny: 0
  Versionify::Dispatch: 0
  XML::Quote: 0
  YAML: 0
resources:
  repository: http://github.com/cebjyre/Task-BeLike-Cebjyre
version: 0.8.0
